### ISSUE TITLE
[L2T] Time Out Issue

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#39]
Hi Lyly,

Would you please kindly check the following the method of org.apache.commons.math.analysis.integration.TrapezoidIntegrator.integrate(UnivariateRealFunction f, double min, double max)? The coverage of such method is 0, but is works fine previously. I debug a while and find that it looks like the problem occurs due to you change the timout setting. Would you please kindly have a check for this issue? 

Relating this issue and bug fix commits would help me to understand your code. So I leave the bug here instead of notifying by email.

Thanks!

**Comment by lylytran** [comment]
timeout setting? in which method?

**Comment by llmhyy** [comment]
I rerun it again. It shows a new exception as follows:

sav.common.core.SavRtException: class not found - [Lorg.apache.commons.math.analysis.polynomials.PolynomialFunction;
	at gentest.core.data.type.VarArrayType.getRawType(VarArrayType.java:62)
	at gentest.core.value.generator.ValueGeneratorMediator.append(ValueGeneratorMediator.java:81)
	at gentest.core.value.generator.ValueGeneratorMediator.append(ValueGeneratorMediator.java:49)
	at gentest.core.value.generator.ValueGenerator.appendVariable(ValueGenerator.java:47)
	at gentest.core.value.generator.ObjectValueGenerator.appendConstructor(ObjectValueGenerator.java:89)
	at gentest.core.value.generator.ObjectValueGenerator.doAppendVariable(ObjectValueGenerator.java:53)
	at gentest.core.value.generator.ExtObjectValueGenerator.doAppendVariable(ExtObjectValueGenerator.java:75)
	at gentest.core.value.generator.ValueGeneratorMediator.append(ValueGeneratorMediator.java:98)
	at gentest.core.value.generator.ValueGeneratorMediator.generate(ValueGeneratorMediator.java:44)
	at gentest.core.ParameterSelector.selectGeneratedParam(ParameterSelector.java:66)
	at gentest.core.ParameterSelector.selectParam(ParameterSelector.java:57)
	at gentest.core.ParameterSelector.selectParam(ParameterSelector.java:46)
	at gentest.core.TestcaseGenerator.selectParams(TestcaseGenerator.java:129)
	at gentest.core.TestcaseGenerator.selectParams(TestcaseGenerator.java:119)
	at gentest.core.TestcaseGenerator.generateSequence(TestcaseGenerator.java:87)
	at gentest.core.RandomTester.test(RandomTester.java:66)
	at gentest.builder.RandomTraceGentestBuilder.doGenerate(RandomTraceGentestBuilder.java:46)
	at gentest.builder.GentestBuilder.generate(GentestBuilder.java:131)
	at learntest.main.TestGenerator.genTest(TestGenerator.java:52)
	at learntest.handler.GenerateTestHandler.generateTest(GenerateTestHandler.java:63)
	at learntest.handler.GenerateTestHandler$1.run(GenerateTestHandler.java:48)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Would you please kindly have a check? I debug the code in the line 92 of LearnTest.java, the `tcExecutor.run();` does not have any result (pls check line 93).

**Comment by lylytran** [comment]
you mean timeout in tcExecutor was changed? I didn't do it.

**Comment by lylytran** [comment]
about the coverage result. Because it depends on the generated testcase which is changed everytime you run Learntest, so it makes sense that you can get difference codecoverage value for each run. 
I run org.apache.commons.math.analysis.integration.TrapezoidIntegrator.integrate 4 times, 2 times the coverage is 0.5, and 2 times the it is 0.0

**Comment by lylytran** [comment]
For classNotFound, I don't know if it is the same case, but I get that exception sometimes at the first run because the eclipse is trying to refresh and rebuild project, so it deletes the project target folder and make our plugin throw exception of classNotFound

**Comment by llmhyy** [comment]
I see, thanks for the update. The problem of coverage 0 would be solved after we change a new CFG.
