### ISSUE TITLE
[L2T] Help Solve the StackOverflowError

### ISSUE THREAD

**Issue by llmhyy** [sunjun-group/Ziyuan#61]
Hi @lylytran,

Please kindly have a check on the stackoverflow error. 

Working method: org.apache.commons.math.linear.ArrayFieldVector.equals, line 813
Exception log:
java.lang.StackOverflowError
	at org.apache.commons.lang3.reflect.TypeUtils.typeVariableToString(TypeUtils.java:1765)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1670)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.parameterizedTypeToString(TypeUtils.java:1797)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1664)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.typeVariableToString(TypeUtils.java:1769)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1670)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.parameterizedTypeToString(TypeUtils.java:1797)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1664)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.typeVariableToString(TypeUtils.java:1769)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1670)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.parameterizedTypeToString(TypeUtils.java:1797)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1664)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.typeVariableToString(TypeUtils.java:1769)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1670)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.parameterizedTypeToString(TypeUtils.java:1797)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1664)
	at org.apache.commons.lang3.reflect.TypeUtils.appendAllTo(TypeUtils.java:1840)
	at org.apache.commons.lang3.reflect.TypeUtils.typeVariableToString(TypeUtils.java:1769)
	at org.apache.commons.lang3.reflect.TypeUtils.toString(TypeUtils.java:1670)

**Comment by llmhyy** [comment]
done
